### ISSUE TITLE
无法查询使用官方服务端的服务器

### ISSUE THREAD

**Issue by thirteenc13** [Miuss/mcapi-pe#1]
无法查询使用bds（官方服务端）的服务器
官方服务端下载地址：https://www.minecraft.net/zh-hans/download/server/bedrock/

**Comment by Miuss** [comment]
麻烦给一下您服务器的IP地址，以便于我修复BUG！

**Comment by thirteenc13** [comment]
> 麻烦给一下您服务器的IP地址，以便于我修复BUG！

mcec.fun:6666
实际上这并不是我的服务器，因为我没有开服务器，该服务器有白名单。
